// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    back: string;
    'color-change': string;
    desc: string;
    filter: string;
    filterItem: string;
    img: string;
    info: string;
    input: string;
    price: string;
    root: string;
    search: string;
    skeleton: string;
    statusBar: string;
    tag: string;
    title: string;
  }
  export const cssExports: CssExports;
  export default cssExports;
  