// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    content: string;
    desc: string;
    kv: string;
    'kv-img': string;
    'series-img': string;
    'series-name': string;
    'series-name-above': string;
    'sub-title': string;
    'theme-title': string;
    themeV2: string;
    title: string;
    'title-info': string;
  }
  export const cssExports: CssExports;
  export default cssExports;
  